<?php

$ranksetNames["mario"] = "Mario";

$ranksetData["mario"] = array(
	array("num" => 0, "image" => '', "text" => 'Non-poster'),
	array("num" => 1, "image" => '', "text" => 'Newcomer'),
	array("num" => 10, "image" => 'microgoomba.gif', "text" => 'Micro-Goomba'),
	array("num" => 20, "image" => 'goomba.gif', "text" => 'Goomba'),
	array("num" => 35, "image" => 'redgoomba.gif', "text" => 'Red Goomba'),
	array("num" => 50, "image" => 'redparagoomba.gif', "text" => 'Red Paragoomba'),
	array("num" => 65, "image" => 'paragoomba.gif', "text" => 'Paragoomba'),
	array("num" => 80, "image" => 'shyguy.gif', "text" => 'Shyguy'),
	array("num" => 100, "image" => 'koopa.gif', "text" => 'Koopa'),
	array("num" => 120, "image" => 'redkoopa.gif', "text" => 'Red Koopa'),
	array("num" => 140, "image" => 'paratroopa.gif', "text" => 'Paratroopa'),
	array("num" => 160, "image" => 'redparatroopa.gif', "text" => 'Red Paratroopa'),
	array("num" => 180, "image" => 'cheepcheep.gif', "text" => 'Cheep-cheep'),
	array("num" => 200, "image" => 'redcheepcheep.gif', "text" => 'Red Cheep-cheep'),
	array("num" => 225, "image" => 'ninji.gif', "text" => 'Ninji'),
	array("num" => 250, "image" => 'flurry.gif', "text" => 'Flurry'),
	array("num" => 275, "image" => 'snifit.gif', "text" => 'Snifit'),
	array("num" => 300, "image" => 'porcupo.gif', "text" => 'Porcupo'),
	array("num" => 325, "image" => 'panser.gif', "text" => 'Panser'),
	array("num" => 350, "image" => 'mole.gif', "text" => 'Mole'),
	array("num" => 375, "image" => 'buzzybeetle.gif', "text" => 'Buzzy Beetle'),
	array("num" => 400, "image" => 'nipperplant.gif', "text" => 'Nipper Plant'),
	array("num" => 425, "image" => 'bloober.gif', "text" => 'Bloober'),
	array("num" => 450, "image" => 'busterbeetle.gif', "text" => 'Buster Beetle'),
	array("num" => 475, "image" => 'beezo.gif', "text" => 'Beezo'),
	array("num" => 500, "image" => 'bulletbill.gif', "text" => 'Bullet Bill'),
	array("num" => 525, "image" => 'rex.gif', "text" => 'Rex'),
	array("num" => 550, "image" => 'lakitu.gif', "text" => 'Lakitu'),
	array("num" => 575, "image" => 'spiny.gif', "text" => 'Spiny'),
	array("num" => 600, "image" => 'bobomb.gif', "text" => 'Bob-Omb'),
	array("num" => 625, "image" => 'drybones.gif', "text" => 'Dry Bones'),
	array("num" => 650, "image" => 'cobrat.gif', "text" => 'Cobrat'),
	array("num" => 675, "image" => 'pokey.gif', "text" => 'Pokey'),
	array("num" => 700, "image" => 'spike.gif', "text" => 'Spike'),
	array("num" => 725, "image" => 'melonbug.gif', "text" => 'Melon Bug'),
	array("num" => 750, "image" => 'lanternghost.gif', "text" => 'Lantern Ghost'),
	array("num" => 775, "image" => 'fuzzy.gif', "text" => 'Fuzzy'),
	array("num" => 800, "image" => 'bandit.gif', "text" => 'Bandit'),
	array("num" => 830, "image" => 'superkoopa.gif', "text" => 'Super Koopa'),
	array("num" => 860, "image" => 'redsuperkoopa.gif', "text" => 'Red Super Koopa'),
	array("num" => 900, "image" => 'boo.gif', "text" => 'Boo'),
	array("num" => 925, "image" => 'boo2.gif', "text" => 'Scary Boo'),
	array("num" => 950, "image" => 'fuzzball.gif', "text" => 'Fuzz Ball'),
	array("num" => 1000, "image" => 'boomerangbrother.gif', "text" => 'Boomerang Brother'),
	array("num" => 1050, "image" => 'hammerbrother.gif', "text" => 'Hammer Brother'),
	array("num" => 1100, "image" => 'firebrother.gif', "text" => 'Fire Brother'),
	array("num" => 1150, "image" => 'firesnake.gif', "text" => 'Fire Snake'),
	array("num" => 1200, "image" => 'giantgoomba.gif', "text" => 'Giant Goomba'),
	array("num" => 1250, "image" => 'giantkoopa.gif', "text" => 'Giant Koopa'),
	array("num" => 1300, "image" => 'giantredkoopa.gif', "text" => 'Giant Red Koopa'),
	array("num" => 1350, "image" => 'giantparatroopa.gif', "text" => 'Giant Paratroopa'),
	array("num" => 1400, "image" => 'giantredparatroopa.gif', "text" => 'Giant Red Paratroopa'),
	array("num" => 1450, "image" => 'chuck.gif', "text" => 'Chuck'),
	array("num" => 1500, "image" => 'thwomp.gif', "text" => 'Thwomp'),
	array("num" => 1550, "image" => 'bossbass.gif', "text" => 'Boss Bass'),
	array("num" => 1600, "image" => 'volcanolotus.gif', "text" => 'Volcano Lotus'),
	array("num" => 1650, "image" => 'lavalotus.gif', "text" => 'Lava Lotus'),
	array("num" => 1700, "image" => 'ptooie.gif', "text" => 'Ptooie'),
	array("num" => 1800, "image" => 'sledgebrother.gif', "text" => 'Sledge Brother'),
	array("num" => 1900, "image" => 'boomboom.gif', "text" => 'Boomboom'),
	array("num" => 2000, "image" => 'birdo.gif', "text" => 'Birdo'),
	array("num" => 2100, "image" => 'redbirdo.gif', "text" => 'Red Birdo'),
	array("num" => 2200, "image" => 'greenbirdo.gif', "text" => 'Green Birdo'),
	array("num" => 2300, "image" => 'larrykoopa.gif', "text" => 'Larry Koopa'),
	array("num" => 2400, "image" => 'mortonkoopa.gif', "text" => 'Morton Koopa'),
	array("num" => 2500, "image" => 'wendykoopa.gif', "text" => 'Wendy Koopa'),
	array("num" => 2600, "image" => 'iggykoopa.gif', "text" => 'Iggy Koopa'),
	array("num" => 2700, "image" => 'roykoopa.gif', "text" => 'Roy Koopa'),
	array("num" => 2800, "image" => 'lemmykoopa.gif', "text" => 'Lemmy Koopa'),
	array("num" => 2900, "image" => 'ludwigvonkoopa.gif', "text" => 'Ludwig Von Koopa'),
	array("num" => 3000, "image" => 'triclyde.gif', "text" => 'Triclyde'),
	array("num" => 3100, "image" => 'magikoopa.gif', "text" => 'Magikoopa'),
	array("num" => 3200, "image" => 'wart.gif', "text" => 'Wart'),
	array("num" => 3300, "image" => 'babybowser.gif', "text" => 'Baby Bowser'),
	array("num" => 3400, "image" => 'kingbowserkoopa.gif', "text" => 'King Bowser Koopa'),
	array("num" => 3500, "image" => 'yoshi.gif', "text" => 'Yoshi'),
	array("num" => 3600, "image" => 'yellowyoshi.gif', "text" => 'Yellow Yoshi'),
	array("num" => 3700, "image" => 'blueyoshi.gif', "text" => 'Blue Yoshi'),
	array("num" => 3800, "image" => 'redyoshi.gif', "text" => 'Red Yoshi'),
	array("num" => 3900, "image" => 'kingyoshi.gif', "text" => 'King Yoshi'),
	array("num" => 4000, "image" => 'babymario.gif', "text" => 'Baby Mario'),
	array("num" => 4100, "image" => 'luigi.gif', "text" => 'Luigi'),
	array("num" => 4200, "image" => 'mario.gif', "text" => 'Mario'),
	array("num" => 4300, "image" => 'superluigi.gif', "text" => 'Super Luigi'),
	array("num" => 4400, "image" => 'supermario.gif', "text" => 'Super Mario'),
	array("num" => 4500, "image" => 'fireluigi.gif', "text" => 'Fire Luigi'),
	array("num" => 4600, "image" => 'firemario.gif', "text" => 'Fire Mario'),
	array("num" => 4700, "image" => 'capeluigi.gif', "text" => 'Cape Luigi'),
	array("num" => 4800, "image" => 'capemario.gif', "text" => 'Cape Mario'),
	array("num" => 4900, "image" => 'starluigi.gif', "text" => 'Star Luigi'),
	array("num" => 5000, "image" => 'starmario.gif', "text" => 'Star Mario')
);
